Fix gdnative lib generation script with python3
Building with python3 was generating this error:
  File "C:\webrtc-native\SConstruct", line 15, in gen_gdnative_lib
    w.write(source[0].get_contents().replace('{GDNATIVE_PATH}', os.path.splitext(t.name)[0]).replace('{TARGET}', env['target']))
TypeError: a bytes-like object is required, not 'str'